# Generated by Django 3.2.6 on 2022-03-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('codigo_estudiante', models.IntegerField(primary_key=True, serialize=False)),
                ('documento_identidad', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('carrera', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
    ]
