# Generated by Django 3.2.6 on 2022-03-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigo_estudiante', models.IntegerField(primary_key=True, serialize=False)),
                ('documento_identidad', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('celular', models.IntegerField()),
                ('carrera', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('password_repeat', models.CharField(max_length=20)),
            ],
        ),
    ]
