# Generated by Django 3.2.6 on 2022-03-18 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gustos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musica', models.CharField(max_length=500)),
                ('deportes', models.CharField(max_length=500)),
                ('series', models.CharField(max_length=500)),
                ('videojuegos', models.CharField(max_length=500)),
                ('literatura', models.CharField(max_length=500)),
                ('codigo_estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
