# Generated by Django 3.2.6 on 2022-04-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20220325_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'psicologo',
                'verbose_name_plural': 'psicologos',
            },
        ),
    ]
