# Generated by Django 3.2.6 on 2022-04-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20220427_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='fecha_publicacion',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='hora_publicacion',
            field=models.CharField(max_length=10),
        ),
    ]
