# Generated by Django 4.0.2 on 2022-05-03 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_usuario_amigos_solicitud_amistad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud_amistad',
            options={'verbose_name': 'solicitud', 'verbose_name_plural': 'solicituds'},
        ),
    ]
