# Generated by Django 3.2.6 on 2022-05-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_solicitud_amistad_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password_repeat',
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(default='images/foto_perfil/nullprofile.jpg', upload_to='images/foto_perfil/'),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images/publicaciones/'),
        ),
    ]
