# Generated by Django 3.2.6 on 2022-06-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='imagen',
            field=models.ImageField(null=True, upload_to='publicaciones/'),
        ),
    ]
